# Generated by Django 2.0.5 on 2018-06-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='alias',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
