# Generated by Django 2.0.5 on 2018-06-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
